<?php
// @see https://www.mediawiki.org/wiki/Manual:Configuration_settings
# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
    exit;
}
##########################################################################
##	Configuration settings											    ##
##	See https://www.mediawiki.org/wiki/Manual:Configuration_setting 	##
##  for an index of all supported configuration settings. 				##
##########################################################################


### Extra Configuration Settings ###


## Debug
## See https://www.mediawiki.org/wiki/Manual:How_to_debug
$wgShowExceptionDetails = true;
#$wgShowDebugToolbar = true;
#$wgShowDebug = true;
#$wgDebugDumpSql = true;
#$wgDebugLogFile = "/config/log/mediawiki/debug.log";


## Logo and Favicon
## $wgLogo is set in LocalSettings.php when it's generated by the installer
## Simply upload your favicon.ico to the root of your domain/subdomain,
## make sure file name is in lower case and its name is "favicon.ico"
## or uncomment below and set you own path.
#$wgFavicon = "/path/to/your/favicon.ico";


## Short URLs
## See https://www.mediawiki.org/wiki/Manual:Short_URL
## $wgScriptPath = ""; //defined in LocalSettings.php
$wgArticlePath = "/$1";
$wgUsePathInfo = true;
$wgScriptExtension = ".php";


## User Rights
## See https://www.mediawiki.org/wiki/Manual:User_rights
// Make wiki private
#$wgGroupPermissions['*']['read'] = false;
#$wgGroupPermissions['*']['createaccount'] = false;
#$wgGroupPermissions['*']['edit'] = false;


## File Uploads
## See https://www.mediawiki.org/wiki/Manual:Configuring_file_uploads
#$wgEnableUploads = true; # Enable uploads, uncomment this if you didn't enable file uploads during the MediaWiki installer and want to enable now
// Uncomment below to use docker volume /assets upload path or set your own path
#$wgUploadPath = "/assets";
#$wgUploadDirectory = "/assets";
// Maximum file upload size
// If you increase this valve you must also update the config/php/php-local.ini file
#$wgUploadSizeWarning = 1073741824; // 1024*1024*1024 = 1 GB
#$wgMaxUploadSize = 1073741824; // 1024*1024*1024 = 1 GB
// Allowed file extension types
#$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'doc',
#    'xls', 'mpp', 'pdf', 'ppt', 'tiff', 'bmp', 'docx', 'xlsx',
#    'pptx', 'ps', 'odt', 'ods', 'odp', 'odg'
#);
// Uploading directly from a URLs
#$wgAllowCopyUploads = true;
#$wgCopyUploadsFromSpecialUpload = true;


## Copyright
## See https://www.mediawiki.org/wiki/Manual:Configuration_settings#Copyright
## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
#$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
#$wgRightsUrl = "";
#$wgRightsText = "";
#$wgRightsIcon = "";


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

