#!/usr/bin/with-contenv bash

# variables
extention_name=null

# source functions
. /etc/mw-maintenance.d/extension-manager.func
. /etc/mw-maintenance.d/database.func

# functions
load_header(){
	clear
	echo "#####################################"
	echo "##                                 ##"
	echo "##      MediaWiki Maintenance      ##"
	echo "##                                 ##"
	echo "##$menu_title##"
	echo "##                                 ##"
	echo "#####################################"
	echo
}

press_to_continue(){
	echo
	read -p 'press enter to continue...' null
}

not_valid_option(){
	echo "Not a valid option"
	sleep 2
}

select_option(){
	# pick out selected name from numbered array of list
	selected_number=$1
	pattern="[0-9]"
	# single character selections won't match/assign
	if [[ "$selected_number" =~ $pattern ]] && [[ $selected_number -lt $option_num ]] && [[ $selected_number -gt 0 ]]
		then
			if [ "$(sed -rn "s/.*^$selected_number\)([A-Za-z0-9\_]\S+|[A-Za-z0-9\_]).*/\1/p" <<<"$option_array")" == "" ]
				then
					# assign numbers 2 through ...
					selected_name="$(sed -rn "s/.* $selected_number\)([A-Za-z0-9\_]\S+|[A-Za-z0-9\_]).*/\1/p" <<<"$option_array")"
				else
					# assign number 1
					selected_name="$(sed -rn "s/.*^$selected_number\)([A-Za-z0-9\_]\S+|[A-Za-z0-9\_]).*/\1/p" <<<"$option_array")"
			fi
		else
			echo "Not a valid selection"
			return 1
	fi
	if [ "$selected_name" == "" ]
		then
			echo "Error with selected name"
			return 2
	fi
}

# sub menus
extension_manager_submenu(){
	submenuL1_option=0
	until [ $submenuL1_option = 8 ]
		do
					  ##6     MediaWiki Maintenance     6##
					  ##8       Extension Manager       8##
			menu_title="        Extension Manager        "
			load_header
			echo "1) Add wfLoadExtension Type"
			echo "2) Add requireExtension Type"
			echo "3) Add Composer Extension"
			echo "4) Remove Extension"
			echo "5) Bulk Changes"
			echo "6) Update Database"
			echo "7) List Installed Extensions"
			echo "8) Back"
			echo
			read -p 'Option: ' submenuL1_option
			echo
			case $submenuL1_option in
						1)
						echo "Add wfLoadExtension Type"
						read -p 'Enter extention name: ' extention_name
						extension_add_wfLoad_type $extention_name
						press_to_continue
						;;

						2)
						echo "Add requireExtension Type"
						read -p 'Enter extention name: ' extention_name
						extension_add_require_type $extention_name
						press_to_continue
						;;

						3)
						echo "Add Composer Extension"
						read -p 'Enter Packagist package name (e.g. mediawiki/maps): ' composer_package
						read -p 'Enter version constraint (e.g. ~14.0): ' composer_version
						read -p 'Enter extension name (must match extensions/ dir it installs as, e.g. Maps): ' composer_extname
						extension_add_composer_type "$composer_package" "$composer_version" "$composer_extname"
						press_to_continue
						;;

						4)
						echo "Remove Extension"
						extension_list
						if [ $? = 0 ] # if list_extension returns 0
							then
								echo
								echo "ALL) Remove all"
								echo
								read -p 'Enter a number or ALL: ' extension_number
								if [ "$extension_number" == "ALL" ]
									then
										read -p 'Are you sure Y/n? ' certainty
										if [ "$certainty" == "Y" ]
											then
												read -p 'Verbose: Y/n? ' sub_option
												if [ "$sub_option" == "Y" ]
													then
														extension_remove_all -v
													else
														extension_remove_all
												fi
											else
												echo "Cancelled"
										fi
									else
										echo
										select_option $extension_number
										if [ $? = 0 ]
											then
												read -p 'Verbose: Y/n? ' sub_option
												if [ "$sub_option" == "Y" ]
													then
														extension_remove $selected_name -v
													else
														extension_remove $selected_name
												fi
										fi
								fi
						fi
						press_to_continue
						;;

						5)
						extension_manager_bulk_submenu
						;;

						6)
						echo "Update Database"
						update_db
						press_to_continue
						;;

						7)
						echo "List Installed Extensions"
						extension_list
						press_to_continue
						;;

						8)
						;;

						*)
						not_valid_option
						;;
					esac
		done
	return
}

extension_manager_bulk_submenu(){
	submenuL2_option=0
	until [ $submenuL2_option = 4 ]
		do
					  ##6     MediaWiki Maintenance     6##
					  ##7      Extension Bulk Edit      7##
			menu_title="       Extension Bulk Edit       "
			load_header
			echo "1) Bulk Edit"
			echo "2) Run Bulk Edit"
			echo "3) Help"
			echo "4) Back"
			echo
			read -p 'Option: ' submenuL2_option
			echo
			case $submenuL2_option in
						1)
						# echo "Bulk Edit"
						nano $EXTENSION_MANAGER_PATH/MANAGER
						;;

						2)
						echo "Run Bulk Edit"
						extension_bulk_edit_run
						press_to_continue
						;;

						3)
						cat /etc/mw-maintenance.d/help_bulk_edit.nfo
						press_to_continue
						;;

						4)
						;;

						*)
						not_valid_option
						;;
					esac
		done
	return
}

database_submenu(){
	submenuL1_option=0
	until [ $submenuL1_option = 4 ]
		do
					  ##6     MediaWiki Maintenance     6##
					  ##9        Database Manager       8##
			menu_title="         Database Manager        "
			load_header
			echo "1) Update Database Schema"
			echo "2) Lock Database"
			echo "3) Unlock Database"
			echo "4) Back"
			echo
			read -p 'Option: ' submenuL1_option
			echo
			case $submenuL1_option in
						1)
						update_db
						press_to_continue
						;;

						2)
						lock_db
						press_to_continue
						;;

						3)
						unlock_db
						press_to_continue
						;;

						4)
						;;

						*)
						not_valid_option
						;;
					esac
		done
	return
}

# main menu
# NOTE: Backups and Services submenus are ported in a later phase of the
# edge-port effort (they need real adaptation for the modernized
# architecture - e.g. dropping the standalone-Parsoid service item and
# adding split-container DB backup support - rather than a blind copy from
# edge). This menu will grow back to edge's full 4-option parity once those
# pieces land.
main_menu(){
	menu_option=0
	until [ $menu_option = 3 ]
		do
					  ##6     MediaWiki Maintenance     6##
					  ##12          Main Menu          12##
			menu_title="            Main Menu            "
			load_header
			echo "1) Extension Manager"
			echo "2) Database"
			echo "3) Quit"
			echo
			read -p 'Option: ' menu_option
			echo
			case $menu_option in
						1)
						extension_manager_submenu
						;;

						2)
						database_submenu
						;;

						3)
						;;

						*)
						not_valid_option
						;;
					esac
		done
}

# start
if [ ! "$testing" == "true" ] # allow 'test' to source all functions and skip straight to a sub menu or use it's own menu
	then
		main_menu
fi
