#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	$MEDIAWIKI_PATH \
	/config/{log/mediawiki,log/parsoid,log/lua,nginx,php,parsoid} \
	/run/s6/services/parsoid \
	/config/assets/resources

# copy mediawiki files
if [ ! -e $MEDIAWIKI_PATH/index.php ]
	then
		echo '### installing mediawiki... ###'
		cp -r $MEDIAWIKI_STORAGE_PATH/. $MEDIAWIKI_PATH
fi

# include extra mediawiki settings
if [ -e $MEDIAWIKI_PATH/LocalSettings.php ] && [ ! -e $MEDIAWIKI_PATH/LocalSettings_Extras.php ]
	then
		echo '### adding extra settings ###'
		cp /defaults/mediawiki/LocalSettings_Extras.php $MEDIAWIKI_PATH/LocalSettings_Extras.php
		sed -i "$ a # Load extra settings" $MEDIAWIKI_PATH/LocalSettings.php
		sed -i "$ a require 'LocalSettings_Extras.php';" $MEDIAWIKI_PATH/LocalSettings.php
fi

# include extension mediawiki settings
if [ -e $MEDIAWIKI_PATH/LocalSettings.php ] && [ ! -e $MEDIAWIKI_PATH/LocalSettings_Extensions.php ]
	then
		echo '### adding extension settings ###'
		cp /defaults/mediawiki/LocalSettings_Extensions.php $MEDIAWIKI_PATH/LocalSettings_Extensions.php
		sed -i "$ a # Load extension settings" $MEDIAWIKI_PATH/LocalSettings.php
		sed -i "$ a require 'LocalSettings_Extensions.php';" $MEDIAWIKI_PATH/LocalSettings.php
fi

# comment out default $wgLogo in LocalSettings.php to avoid conflict with LocalSettings_Extras.php
[[ -f $MEDIAWIKI_PATH/LocalSettings.php ]] && \
	sed -i "s/^\$wgLogo/\#$\wgLogo/g" $MEDIAWIKI_PATH/LocalSettings.php

# Add default logo if missing
[[ ! -f /config/assets/logo.png ]] && \
	cp $MEDIAWIKI_STORAGE_PATH/resources/assets/mediawiki.png /config/assets/resources/logo.png
	
# Add default favicon if missing
[[ ! -f /config/assets/favicon.ico ]] && \
	cp $MEDIAWIKI_STORAGE_PATH/resources/assets/mediawiki.png /config/assets/resources/favicon.ico

# copy config files
echo '### copying config files... ###'
# nginx
[[ ! -f /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx/wiki-nginx.conf /config/nginx/nginx.conf && \
	echo 'default nginx.conf copied'
# php
[[ ! -f /config/php/php-local.ini ]] && \
	cp /defaults/php/php.ini /config/php/php-local.ini && \
	echo 'default php.ini copied'
# php-fpm
[[ ! -f /config/php/www2.conf ]] && \
	cp /defaults/php/php-fpm.conf /config/php/www2.conf && \
	echo 'default php-fpm.conf copied'
# parsoid
[[ ! -f /config/parsoid/config.yaml ]] && \
	cp /defaults/parsoid/config.yaml /config/parsoid/config.yaml && \
	echo 'default parsoid config.yaml copied'
[[ ! -L $PARSOID_HOME/config.yaml && -e $PARSOID_HOME/config.yaml ]] && \
	rm $PARSOID_HOME/config.yaml
[[ ! -L $PARSOID_HOME/config.yaml ]] && \
	ln -s /config/parsoid/config.yaml $PARSOID_HOME/config.yaml

# set set execute permissions for mediawiki extentions
chmod a+x $MEDIAWIKI_PATH/extensions/SyntaxHighlight_GeSHi/pygments/pygmentize
chmod a+x $MEDIAWIKI_PATH/extensions/Scribunto/includes/engines/LuaStandalone/binaries/lua5_1_5_linux_64_generic/lua

# run composer for TemplateStyles if needed
if [ ! -d $MEDIAWIKI_PATH/extensions/TemplateStyles/vendor ]
	then
		cd $MEDIAWIKI_PATH/extensions/TemplateStyles
		composer install --no-dev
		chown -R abc:abc $MEDIAWIKI_PATH/extensions/TemplateStyles
fi

# set ownership and permissions for mediawiki to use docker volume /assets directory for file uploads
chown -R abc:abc /config/assets
chmod -R 664 /config/assets


