#!/usr/bin/with-contenv bash

# upgrade mediawiki part 2
if [ -e $MEDIAWIKI_PATH/VERSION ]
	then
		# update database if upgrade mediawiki step 1 has executed
		if [ "upgrading to $MEDIAWIKI_VERSION" == "$(cat $MEDIAWIKI_PATH/VERSION)" ]
			then
				# upgrade extensions added with ExtensionManager
				INSTALLED=`cat $EXTENSION_MANAGER_PATH/INSTALLED`
				for EXTENSION in $INSTALLED
					do
						echo "ExtensionManager: upgrading $EXTENSION extension"
						rm -rf $MEDIAWIKI_EXTENSION_PATH/$EXTENSION
						mkdir -p $MEDIAWIKI_EXTENSION_PATH/$EXTENSION
						git clone \
							--branch ${MEDIAWIKI_BRANCH} \
							--single-branch \
							--depth 1 \
							https://gerrit.wikimedia.org/r/mediawiki/extensions/$EXTENSION \
							$MEDIAWIKI_EXTENSION_PATH/$EXTENSION
						cd $MEDIAWIKI_EXTENSION_PATH/$EXTENSION
						git submodule update --init
						rm -rf $MEDIAWIKI_EXTENSION_PATH/$EXTENSION/.git*
					done
				# upgrade mediawiki database
				echo 'upgrading mediawiki database'
				cd $MEDIAWIKI_PATH/maintenance
				if php update.php --quick
					then
						sed -i "s/.*/$MEDIAWIKI_VERSION/" $MEDIAWIKI_PATH/VERSION
					else
						echo "ERROR: update.php failed - database was NOT fully migrated to $MEDIAWIKI_VERSION"
						echo "VERSION file left as 'upgrading to $MEDIAWIKI_VERSION' so this is retried on next restart"
						echo "instead of silently marking the upgrade complete against a half-migrated database"
						exit 1
				fi
		fi
	else
		# version control file does not exist, create it and set version if mediawiki has been installed (incase 15-config fails) 
		if [ -e $MEDIAWIKI_PATH/index.php ]
			then
				echo 'adding version control'
				cd $MEDIAWIKI_PATH
				> VERSION
				echo $MEDIAWIKI_VERSION > VERSION  # full version numbering
		fi
fi
