#!/usr/bin/with-contenv bash

# upgrade Alpine packages
if [ $APK_UPGRADE == true ]
	then
		echo "### upgrading alpine packages ###"
		apk update
		apk upgrade
fi

# upgrade mediawiki part-1, (merged from 12-upgrade)
# test for version control file
if [ -f $MEDIAWIKI_PATH/VERSION ]
	then
		# check if upgrading mediawiki is enabled after version control file check
		if [ $UPGRADE_MEDIAWIKI == 'enable' ]
			then
				# compare docker-mediawiki version to version control file if upgrading is enabled
				echo "### mediawiki upgrade enabled ###"
				if [ "$MEDIAWIKI_VERSION" != "$(cat $MEDIAWIKI_PATH/VERSION)" ]
					then
						. /etc/mw-maintenance.d/backup.func #source
						backup_all #function
						echo "### upgrading mediawiki to $MEDIAWIKI_VERSION ###"
						rm -f $MEDIAWIKI_PATH/index.php
						sed -i "s/.*/upgrading to $MEDIAWIKI_VERSION/" $MEDIAWIKI_PATH/VERSION
				fi
			else
				echo "### mediawiki upgrade disabled ###"
		fi
	else 
		echo "### mediawiki not yet installed ###"
fi

# copy mediawiki files
if [ ! -f $MEDIAWIKI_PATH/index.php ]
	then
		echo "### coping files... ###"
		cp -r $MEDIAWIKI_STORAGE_PATH/. $MEDIAWIKI_PATH
fi

# upgrade mediawiki part 2
if [ -f $MEDIAWIKI_PATH/VERSION ]
	then
		# update database if upgrade mediawiki step 1 has executed
		if [ "upgrading to $MEDIAWIKI_VERSION" == "$(cat $MEDIAWIKI_PATH/VERSION)" ]
			then
				# source functions
				. /etc/mw-maintenance.d/extension-manager.func
				. /etc/mw-maintenance.d/database.func
				# upgrade extensions added with ExtensionManager
				extension_upgrade
				# upgrade mediawiki database
				echo "### upgrading mediawiki database ###"
				if [ -d "$MYSQL_DBDATA_PATH/mysql" ] && [ $MYSQL_INSTALL_OPTION == true ] # check if using internal MariaDB and a database exists
					then
						# start mysql deamon, update database schema, kill mysql deamon
						mysqld > /dev/null 2>&1 &
						pid="$!"
						sleep 1
						update_db
						kill $pid
					else
						update_db
				fi
				sed -i "s/.*/$MEDIAWIKI_VERSION/" $MEDIAWIKI_PATH/VERSION
		fi
	else
		# version control file does not exist, create it and set version if mediawiki has been installed (incase 15-config fails) 
		if [ -e $MEDIAWIKI_PATH/index.php ]
			then
				echo '### adding version control ###'
				cd $MEDIAWIKI_PATH
				> VERSION
				echo $MEDIAWIKI_VERSION > VERSION  # full version numbering
		fi
fi
