#!/usr/bin/with-contenv bash

# source functions
. /etc/mw-maintenance.d/extension-manager.func

# upgrade mediawiki part 2
if [ -e $MEDIAWIKI_PATH/VERSION ]
	then
		# update database if upgrade mediawiki step 1 has executed
		if [ "upgrading to $MEDIAWIKI_VERSION" == "$(cat $MEDIAWIKI_PATH/VERSION)" ]
			then
				# upgrade extensions added with ExtensionManager
				extension_upgrade
				# upgrade mediawiki database
				echo 'upgrading mediawiki database'
				cd $MEDIAWIKI_PATH/maintenance
				if php update.php --quick
					then
						sed -i "s/.*/$MEDIAWIKI_VERSION/" $MEDIAWIKI_PATH/VERSION
					else
						echo "ERROR: update.php failed - database was NOT fully migrated to $MEDIAWIKI_VERSION"
						echo "VERSION file left as 'upgrading to $MEDIAWIKI_VERSION' so this is retried on next restart"
						echo "instead of silently marking the upgrade complete against a half-migrated database"
						exit 1
				fi
		fi
	else
		# version control file does not exist, create it and set version if mediawiki has been installed (incase 15-config fails) 
		if [ -e $MEDIAWIKI_PATH/index.php ]
			then
				echo 'adding version control'
				cd $MEDIAWIKI_PATH
				> VERSION
				echo $MEDIAWIKI_VERSION > VERSION  # full version numbering
		fi
fi
