#!/usr/bin/with-contenv bash

if [ -e $EXTENSION_MANAGER_PATH/MANAGER ] && [ -e $EXTENSION_MANAGER_PATH/INSTALLED ]
	then
		until [ "$(cat $EXTENSION_MANAGER_PATH/MANAGER)" == "" ] || [ "$EXTENSION_STATUS" == "error" ]
			do
				EXTENSION_STATUS=$(sed -n 1p $EXTENSION_MANAGER_PATH/MANAGER) && \
				EXTENSION="${EXTENSION_STATUS//[+-]}"
				# add extension
				if [ $EXTENSION_STATUS == +$EXTENSION ]
					then
						echo "ExtensionManager: installing $EXTENSION extension" && \
						mkdir -p $MEDIAWIKI_EXTENSION_PATH/$EXTENSION && \
						git clone \
							--branch ${MEDIAWIKI_BRANCH} \
							--single-branch \
							--depth 1 \
							https://gerrit.wikimedia.org/r/mediawiki/extensions/$EXTENSION \
							$MEDIAWIKI_EXTENSION_PATH/$EXTENSION && \
						cd $MEDIAWIKI_EXTENSION_PATH/$EXTENSION && \
						git submodule update --init && \
						rm -rf $MEDIAWIKI_EXTENSION_PATH/$EXTENSION/.git*
						sed -i "$ a wfLoadExtension( '$EXTENSION' ); #https://www.mediawiki.org/wiki/Extension:$EXTENSION" $MEDIAWIKI_PATH/LocalSettings.php && \
						echo $EXTENSION >> $EXTENSION_MANAGER_PATH/INSTALLED && \
						sed -i 1d $EXTENSION_MANAGER_PATH/MANAGER
				# remove extension
				elif [ $EXTENSION_STATUS == -$EXTENSION ]
					then
						echo "ExtensionManager: removing $EXTENSION extension" && \
						rm -rf $MEDIAWIKI_EXTENSION_PATH/$EXTENSION
						sed -i "/$EXTENSION/d" $MEDIAWIKI_PATH/LocalSettings.php && \
						sed -i "/$EXTENSION/d" $EXTENSION_MANAGER_PATH/INSTALLED && \
						sed -i 1d $EXTENSION_MANAGER_PATH/MANAGER
				else
					echo "ExtensionManager: operator not specified"
					echo "ExtensionManager: correct MANAGER file and try again"
					EXTENSION_STATUS="error"
				fi
			done
		chown -R abc:abc $MEDIAWIKI_EXTENSION_PATH
	else
		if [ -e $MEDIAWIKI_PATH/LocalSettings.php ]
			then
				# make files if missing and add statement if LocalSettings.php has been generated
				mkdir -p $EXTENSION_MANAGER_PATH
				echo '' > $EXTENSION_MANAGER_PATH/MANAGER
				echo '' > $EXTENSION_MANAGER_PATH/INSTALLED
				cp /etc/cont-init.d/17-extension-manager $EXTENSION_MANAGER_PATH/run
				chown -R abc:abc $EXTENSION_MANAGER_PATH
				cat <<EOT >> $MEDIAWIKI_PATH/LocalSettings.php

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled by extension_manager:

EOT
		fi
fi

