#!/usr/bin/with-contenv bash

# source functions
. /etc/mw-maintenance.d/extension-manager.func

# start extension_bulk_edit_run, will setup 1st if $EXTENSION_MANAGER_PATH/MANAGER missing
extension_bulk_edit_run